server:
  port: 8080
  servlet:
    context-path: /manager

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/manager_stadium
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB  # Tăng giới hạn file lên 50MB
      max-request-size: 50MB # Tăng giới hạn request lên 50MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: hatruong06012003@gmail.com
    password: jginiiadneqboqpa
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

minio:
  url: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: manager
  bucketName2: field
  bucketName3: services
  bucketName4: facility

vnpay:
  version: 2.1.0
  command: pay
  tmnCode: U4EVMUZ4
  hashSecret: U07G1GYBZGEA0NM42QPL7JJCQR1LH2L1
  payUrl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  returnUrl: http://localhost:3000/payment-success

jwt:
  signerKey: "W7B+tP+Dejy4R6RSdnl/eegEfsBI2c4jCoIyWdmzUzy1MzSC4Ky5HqdQ/6N1yUgs"
  valid-duration: 3600
  refreshable-duration: 120

